// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"notifex/ent/apikey"
	"notifex/ent/app"
	"notifex/ent/notification"
	"notifex/ent/notificationlog"
	"notifex/ent/predicate"
	"notifex/ent/template"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AppUpdate is the builder for updating App entities.
type AppUpdate struct {
	config
	hooks    []Hook
	mutation *AppMutation
}

// Where appends a list predicates to the AppUpdate builder.
func (_u *AppUpdate) Where(ps ...predicate.App) *AppUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *AppUpdate) SetName(v string) *AppUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AppUpdate) SetNillableName(v *string) *AppUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPlan sets the "plan" field.
func (_u *AppUpdate) SetPlan(v app.Plan) *AppUpdate {
	_u.mutation.SetPlan(v)
	return _u
}

// SetNillablePlan sets the "plan" field if the given value is not nil.
func (_u *AppUpdate) SetNillablePlan(v *app.Plan) *AppUpdate {
	if v != nil {
		_u.SetPlan(*v)
	}
	return _u
}

// SetMonthlyQuota sets the "monthly_quota" field.
func (_u *AppUpdate) SetMonthlyQuota(v int) *AppUpdate {
	_u.mutation.ResetMonthlyQuota()
	_u.mutation.SetMonthlyQuota(v)
	return _u
}

// SetNillableMonthlyQuota sets the "monthly_quota" field if the given value is not nil.
func (_u *AppUpdate) SetNillableMonthlyQuota(v *int) *AppUpdate {
	if v != nil {
		_u.SetMonthlyQuota(*v)
	}
	return _u
}

// AddMonthlyQuota adds value to the "monthly_quota" field.
func (_u *AppUpdate) AddMonthlyQuota(v int) *AppUpdate {
	_u.mutation.AddMonthlyQuota(v)
	return _u
}

// SetQuotaUsed sets the "quota_used" field.
func (_u *AppUpdate) SetQuotaUsed(v int) *AppUpdate {
	_u.mutation.ResetQuotaUsed()
	_u.mutation.SetQuotaUsed(v)
	return _u
}

// SetNillableQuotaUsed sets the "quota_used" field if the given value is not nil.
func (_u *AppUpdate) SetNillableQuotaUsed(v *int) *AppUpdate {
	if v != nil {
		_u.SetQuotaUsed(*v)
	}
	return _u
}

// AddQuotaUsed adds value to the "quota_used" field.
func (_u *AppUpdate) AddQuotaUsed(v int) *AppUpdate {
	_u.mutation.AddQuotaUsed(v)
	return _u
}

// SetQuotaResetAt sets the "quota_reset_at" field.
func (_u *AppUpdate) SetQuotaResetAt(v time.Time) *AppUpdate {
	_u.mutation.SetQuotaResetAt(v)
	return _u
}

// SetNillableQuotaResetAt sets the "quota_reset_at" field if the given value is not nil.
func (_u *AppUpdate) SetNillableQuotaResetAt(v *time.Time) *AppUpdate {
	if v != nil {
		_u.SetQuotaResetAt(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *AppUpdate) SetActive(v bool) *AppUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *AppUpdate) SetNillableActive(v *bool) *AppUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AppUpdate) SetUpdatedAt(v time.Time) *AppUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (_u *AppUpdate) AddAPIKeyIDs(ids ...uuid.UUID) *AppUpdate {
	_u.mutation.AddAPIKeyIDs(ids...)
	return _u
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (_u *AppUpdate) AddAPIKeys(v ...*APIKey) *AppUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPIKeyIDs(ids...)
}

// AddTemplateIDs adds the "templates" edge to the Template entity by IDs.
func (_u *AppUpdate) AddTemplateIDs(ids ...uuid.UUID) *AppUpdate {
	_u.mutation.AddTemplateIDs(ids...)
	return _u
}

// AddTemplates adds the "templates" edges to the Template entity.
func (_u *AppUpdate) AddTemplates(v ...*Template) *AppUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTemplateIDs(ids...)
}

// AddNotificationIDs adds the "notifications" edge to the Notification entity by IDs.
func (_u *AppUpdate) AddNotificationIDs(ids ...uuid.UUID) *AppUpdate {
	_u.mutation.AddNotificationIDs(ids...)
	return _u
}

// AddNotifications adds the "notifications" edges to the Notification entity.
func (_u *AppUpdate) AddNotifications(v ...*Notification) *AppUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNotificationIDs(ids...)
}

// AddNotificationlogIDs adds the "notificationlog" edge to the NotificationLog entity by IDs.
func (_u *AppUpdate) AddNotificationlogIDs(ids ...uuid.UUID) *AppUpdate {
	_u.mutation.AddNotificationlogIDs(ids...)
	return _u
}

// AddNotificationlog adds the "notificationlog" edges to the NotificationLog entity.
func (_u *AppUpdate) AddNotificationlog(v ...*NotificationLog) *AppUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNotificationlogIDs(ids...)
}

// Mutation returns the AppMutation object of the builder.
func (_u *AppUpdate) Mutation() *AppMutation {
	return _u.mutation
}

// ClearAPIKeys clears all "api_keys" edges to the APIKey entity.
func (_u *AppUpdate) ClearAPIKeys() *AppUpdate {
	_u.mutation.ClearAPIKeys()
	return _u
}

// RemoveAPIKeyIDs removes the "api_keys" edge to APIKey entities by IDs.
func (_u *AppUpdate) RemoveAPIKeyIDs(ids ...uuid.UUID) *AppUpdate {
	_u.mutation.RemoveAPIKeyIDs(ids...)
	return _u
}

// RemoveAPIKeys removes "api_keys" edges to APIKey entities.
func (_u *AppUpdate) RemoveAPIKeys(v ...*APIKey) *AppUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPIKeyIDs(ids...)
}

// ClearTemplates clears all "templates" edges to the Template entity.
func (_u *AppUpdate) ClearTemplates() *AppUpdate {
	_u.mutation.ClearTemplates()
	return _u
}

// RemoveTemplateIDs removes the "templates" edge to Template entities by IDs.
func (_u *AppUpdate) RemoveTemplateIDs(ids ...uuid.UUID) *AppUpdate {
	_u.mutation.RemoveTemplateIDs(ids...)
	return _u
}

// RemoveTemplates removes "templates" edges to Template entities.
func (_u *AppUpdate) RemoveTemplates(v ...*Template) *AppUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTemplateIDs(ids...)
}

// ClearNotifications clears all "notifications" edges to the Notification entity.
func (_u *AppUpdate) ClearNotifications() *AppUpdate {
	_u.mutation.ClearNotifications()
	return _u
}

// RemoveNotificationIDs removes the "notifications" edge to Notification entities by IDs.
func (_u *AppUpdate) RemoveNotificationIDs(ids ...uuid.UUID) *AppUpdate {
	_u.mutation.RemoveNotificationIDs(ids...)
	return _u
}

// RemoveNotifications removes "notifications" edges to Notification entities.
func (_u *AppUpdate) RemoveNotifications(v ...*Notification) *AppUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNotificationIDs(ids...)
}

// ClearNotificationlog clears all "notificationlog" edges to the NotificationLog entity.
func (_u *AppUpdate) ClearNotificationlog() *AppUpdate {
	_u.mutation.ClearNotificationlog()
	return _u
}

// RemoveNotificationlogIDs removes the "notificationlog" edge to NotificationLog entities by IDs.
func (_u *AppUpdate) RemoveNotificationlogIDs(ids ...uuid.UUID) *AppUpdate {
	_u.mutation.RemoveNotificationlogIDs(ids...)
	return _u
}

// RemoveNotificationlog removes "notificationlog" edges to NotificationLog entities.
func (_u *AppUpdate) RemoveNotificationlog(v ...*NotificationLog) *AppUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNotificationlogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AppUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AppUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AppUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AppUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AppUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := app.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AppUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := app.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "App.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Plan(); ok {
		if err := app.PlanValidator(v); err != nil {
			return &ValidationError{Name: "plan", err: fmt.Errorf(`ent: validator failed for field "App.plan": %w`, err)}
		}
	}
	return nil
}

func (_u *AppUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(app.Table, app.Columns, sqlgraph.NewFieldSpec(app.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(app.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Plan(); ok {
		_spec.SetField(app.FieldPlan, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.MonthlyQuota(); ok {
		_spec.SetField(app.FieldMonthlyQuota, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMonthlyQuota(); ok {
		_spec.AddField(app.FieldMonthlyQuota, field.TypeInt, value)
	}
	if value, ok := _u.mutation.QuotaUsed(); ok {
		_spec.SetField(app.FieldQuotaUsed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuotaUsed(); ok {
		_spec.AddField(app.FieldQuotaUsed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.QuotaResetAt(); ok {
		_spec.SetField(app.FieldQuotaResetAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(app.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(app.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.APIKeysTable,
			Columns: []string{app.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPIKeysIDs(); len(nodes) > 0 && !_u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.APIKeysTable,
			Columns: []string{app.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.APIKeysTable,
			Columns: []string{app.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TemplatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.TemplatesTable,
			Columns: []string{app.TemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTemplatesIDs(); len(nodes) > 0 && !_u.mutation.TemplatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.TemplatesTable,
			Columns: []string{app.TemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TemplatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.TemplatesTable,
			Columns: []string{app.TemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NotificationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.NotificationsTable,
			Columns: []string{app.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNotificationsIDs(); len(nodes) > 0 && !_u.mutation.NotificationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.NotificationsTable,
			Columns: []string{app.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NotificationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.NotificationsTable,
			Columns: []string{app.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NotificationlogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   app.NotificationlogTable,
			Columns: app.NotificationlogPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationlog.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNotificationlogIDs(); len(nodes) > 0 && !_u.mutation.NotificationlogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   app.NotificationlogTable,
			Columns: app.NotificationlogPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationlog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NotificationlogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   app.NotificationlogTable,
			Columns: app.NotificationlogPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationlog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{app.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AppUpdateOne is the builder for updating a single App entity.
type AppUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AppMutation
}

// SetName sets the "name" field.
func (_u *AppUpdateOne) SetName(v string) *AppUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableName(v *string) *AppUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPlan sets the "plan" field.
func (_u *AppUpdateOne) SetPlan(v app.Plan) *AppUpdateOne {
	_u.mutation.SetPlan(v)
	return _u
}

// SetNillablePlan sets the "plan" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillablePlan(v *app.Plan) *AppUpdateOne {
	if v != nil {
		_u.SetPlan(*v)
	}
	return _u
}

// SetMonthlyQuota sets the "monthly_quota" field.
func (_u *AppUpdateOne) SetMonthlyQuota(v int) *AppUpdateOne {
	_u.mutation.ResetMonthlyQuota()
	_u.mutation.SetMonthlyQuota(v)
	return _u
}

// SetNillableMonthlyQuota sets the "monthly_quota" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableMonthlyQuota(v *int) *AppUpdateOne {
	if v != nil {
		_u.SetMonthlyQuota(*v)
	}
	return _u
}

// AddMonthlyQuota adds value to the "monthly_quota" field.
func (_u *AppUpdateOne) AddMonthlyQuota(v int) *AppUpdateOne {
	_u.mutation.AddMonthlyQuota(v)
	return _u
}

// SetQuotaUsed sets the "quota_used" field.
func (_u *AppUpdateOne) SetQuotaUsed(v int) *AppUpdateOne {
	_u.mutation.ResetQuotaUsed()
	_u.mutation.SetQuotaUsed(v)
	return _u
}

// SetNillableQuotaUsed sets the "quota_used" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableQuotaUsed(v *int) *AppUpdateOne {
	if v != nil {
		_u.SetQuotaUsed(*v)
	}
	return _u
}

// AddQuotaUsed adds value to the "quota_used" field.
func (_u *AppUpdateOne) AddQuotaUsed(v int) *AppUpdateOne {
	_u.mutation.AddQuotaUsed(v)
	return _u
}

// SetQuotaResetAt sets the "quota_reset_at" field.
func (_u *AppUpdateOne) SetQuotaResetAt(v time.Time) *AppUpdateOne {
	_u.mutation.SetQuotaResetAt(v)
	return _u
}

// SetNillableQuotaResetAt sets the "quota_reset_at" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableQuotaResetAt(v *time.Time) *AppUpdateOne {
	if v != nil {
		_u.SetQuotaResetAt(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *AppUpdateOne) SetActive(v bool) *AppUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableActive(v *bool) *AppUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AppUpdateOne) SetUpdatedAt(v time.Time) *AppUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (_u *AppUpdateOne) AddAPIKeyIDs(ids ...uuid.UUID) *AppUpdateOne {
	_u.mutation.AddAPIKeyIDs(ids...)
	return _u
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (_u *AppUpdateOne) AddAPIKeys(v ...*APIKey) *AppUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPIKeyIDs(ids...)
}

// AddTemplateIDs adds the "templates" edge to the Template entity by IDs.
func (_u *AppUpdateOne) AddTemplateIDs(ids ...uuid.UUID) *AppUpdateOne {
	_u.mutation.AddTemplateIDs(ids...)
	return _u
}

// AddTemplates adds the "templates" edges to the Template entity.
func (_u *AppUpdateOne) AddTemplates(v ...*Template) *AppUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTemplateIDs(ids...)
}

// AddNotificationIDs adds the "notifications" edge to the Notification entity by IDs.
func (_u *AppUpdateOne) AddNotificationIDs(ids ...uuid.UUID) *AppUpdateOne {
	_u.mutation.AddNotificationIDs(ids...)
	return _u
}

// AddNotifications adds the "notifications" edges to the Notification entity.
func (_u *AppUpdateOne) AddNotifications(v ...*Notification) *AppUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNotificationIDs(ids...)
}

// AddNotificationlogIDs adds the "notificationlog" edge to the NotificationLog entity by IDs.
func (_u *AppUpdateOne) AddNotificationlogIDs(ids ...uuid.UUID) *AppUpdateOne {
	_u.mutation.AddNotificationlogIDs(ids...)
	return _u
}

// AddNotificationlog adds the "notificationlog" edges to the NotificationLog entity.
func (_u *AppUpdateOne) AddNotificationlog(v ...*NotificationLog) *AppUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNotificationlogIDs(ids...)
}

// Mutation returns the AppMutation object of the builder.
func (_u *AppUpdateOne) Mutation() *AppMutation {
	return _u.mutation
}

// ClearAPIKeys clears all "api_keys" edges to the APIKey entity.
func (_u *AppUpdateOne) ClearAPIKeys() *AppUpdateOne {
	_u.mutation.ClearAPIKeys()
	return _u
}

// RemoveAPIKeyIDs removes the "api_keys" edge to APIKey entities by IDs.
func (_u *AppUpdateOne) RemoveAPIKeyIDs(ids ...uuid.UUID) *AppUpdateOne {
	_u.mutation.RemoveAPIKeyIDs(ids...)
	return _u
}

// RemoveAPIKeys removes "api_keys" edges to APIKey entities.
func (_u *AppUpdateOne) RemoveAPIKeys(v ...*APIKey) *AppUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPIKeyIDs(ids...)
}

// ClearTemplates clears all "templates" edges to the Template entity.
func (_u *AppUpdateOne) ClearTemplates() *AppUpdateOne {
	_u.mutation.ClearTemplates()
	return _u
}

// RemoveTemplateIDs removes the "templates" edge to Template entities by IDs.
func (_u *AppUpdateOne) RemoveTemplateIDs(ids ...uuid.UUID) *AppUpdateOne {
	_u.mutation.RemoveTemplateIDs(ids...)
	return _u
}

// RemoveTemplates removes "templates" edges to Template entities.
func (_u *AppUpdateOne) RemoveTemplates(v ...*Template) *AppUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTemplateIDs(ids...)
}

// ClearNotifications clears all "notifications" edges to the Notification entity.
func (_u *AppUpdateOne) ClearNotifications() *AppUpdateOne {
	_u.mutation.ClearNotifications()
	return _u
}

// RemoveNotificationIDs removes the "notifications" edge to Notification entities by IDs.
func (_u *AppUpdateOne) RemoveNotificationIDs(ids ...uuid.UUID) *AppUpdateOne {
	_u.mutation.RemoveNotificationIDs(ids...)
	return _u
}

// RemoveNotifications removes "notifications" edges to Notification entities.
func (_u *AppUpdateOne) RemoveNotifications(v ...*Notification) *AppUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNotificationIDs(ids...)
}

// ClearNotificationlog clears all "notificationlog" edges to the NotificationLog entity.
func (_u *AppUpdateOne) ClearNotificationlog() *AppUpdateOne {
	_u.mutation.ClearNotificationlog()
	return _u
}

// RemoveNotificationlogIDs removes the "notificationlog" edge to NotificationLog entities by IDs.
func (_u *AppUpdateOne) RemoveNotificationlogIDs(ids ...uuid.UUID) *AppUpdateOne {
	_u.mutation.RemoveNotificationlogIDs(ids...)
	return _u
}

// RemoveNotificationlog removes "notificationlog" edges to NotificationLog entities.
func (_u *AppUpdateOne) RemoveNotificationlog(v ...*NotificationLog) *AppUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNotificationlogIDs(ids...)
}

// Where appends a list predicates to the AppUpdate builder.
func (_u *AppUpdateOne) Where(ps ...predicate.App) *AppUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AppUpdateOne) Select(field string, fields ...string) *AppUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated App entity.
func (_u *AppUpdateOne) Save(ctx context.Context) (*App, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AppUpdateOne) SaveX(ctx context.Context) *App {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AppUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AppUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AppUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := app.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AppUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := app.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "App.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Plan(); ok {
		if err := app.PlanValidator(v); err != nil {
			return &ValidationError{Name: "plan", err: fmt.Errorf(`ent: validator failed for field "App.plan": %w`, err)}
		}
	}
	return nil
}

func (_u *AppUpdateOne) sqlSave(ctx context.Context) (_node *App, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(app.Table, app.Columns, sqlgraph.NewFieldSpec(app.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "App.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, app.FieldID)
		for _, f := range fields {
			if !app.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != app.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(app.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Plan(); ok {
		_spec.SetField(app.FieldPlan, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.MonthlyQuota(); ok {
		_spec.SetField(app.FieldMonthlyQuota, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMonthlyQuota(); ok {
		_spec.AddField(app.FieldMonthlyQuota, field.TypeInt, value)
	}
	if value, ok := _u.mutation.QuotaUsed(); ok {
		_spec.SetField(app.FieldQuotaUsed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuotaUsed(); ok {
		_spec.AddField(app.FieldQuotaUsed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.QuotaResetAt(); ok {
		_spec.SetField(app.FieldQuotaResetAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(app.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(app.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.APIKeysTable,
			Columns: []string{app.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPIKeysIDs(); len(nodes) > 0 && !_u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.APIKeysTable,
			Columns: []string{app.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.APIKeysTable,
			Columns: []string{app.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TemplatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.TemplatesTable,
			Columns: []string{app.TemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTemplatesIDs(); len(nodes) > 0 && !_u.mutation.TemplatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.TemplatesTable,
			Columns: []string{app.TemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TemplatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.TemplatesTable,
			Columns: []string{app.TemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NotificationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.NotificationsTable,
			Columns: []string{app.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNotificationsIDs(); len(nodes) > 0 && !_u.mutation.NotificationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.NotificationsTable,
			Columns: []string{app.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NotificationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.NotificationsTable,
			Columns: []string{app.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NotificationlogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   app.NotificationlogTable,
			Columns: app.NotificationlogPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationlog.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNotificationlogIDs(); len(nodes) > 0 && !_u.mutation.NotificationlogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   app.NotificationlogTable,
			Columns: app.NotificationlogPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationlog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NotificationlogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   app.NotificationlogTable,
			Columns: app.NotificationlogPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationlog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &App{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{app.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
