// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"notifex/ent/deliveryattempt"
	"notifex/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DeliveryAttemptUpdate is the builder for updating DeliveryAttempt entities.
type DeliveryAttemptUpdate struct {
	config
	hooks    []Hook
	mutation *DeliveryAttemptMutation
}

// Where appends a list predicates to the DeliveryAttemptUpdate builder.
func (_u *DeliveryAttemptUpdate) Where(ps ...predicate.DeliveryAttempt) *DeliveryAttemptUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the DeliveryAttemptMutation object of the builder.
func (_u *DeliveryAttemptUpdate) Mutation() *DeliveryAttemptMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeliveryAttemptUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeliveryAttemptUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeliveryAttemptUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeliveryAttemptUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *DeliveryAttemptUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(deliveryattempt.Table, deliveryattempt.Columns, sqlgraph.NewFieldSpec(deliveryattempt.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deliveryattempt.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeliveryAttemptUpdateOne is the builder for updating a single DeliveryAttempt entity.
type DeliveryAttemptUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeliveryAttemptMutation
}

// Mutation returns the DeliveryAttemptMutation object of the builder.
func (_u *DeliveryAttemptUpdateOne) Mutation() *DeliveryAttemptMutation {
	return _u.mutation
}

// Where appends a list predicates to the DeliveryAttemptUpdate builder.
func (_u *DeliveryAttemptUpdateOne) Where(ps ...predicate.DeliveryAttempt) *DeliveryAttemptUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeliveryAttemptUpdateOne) Select(field string, fields ...string) *DeliveryAttemptUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DeliveryAttempt entity.
func (_u *DeliveryAttemptUpdateOne) Save(ctx context.Context) (*DeliveryAttempt, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeliveryAttemptUpdateOne) SaveX(ctx context.Context) *DeliveryAttempt {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeliveryAttemptUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeliveryAttemptUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *DeliveryAttemptUpdateOne) sqlSave(ctx context.Context) (_node *DeliveryAttempt, err error) {
	_spec := sqlgraph.NewUpdateSpec(deliveryattempt.Table, deliveryattempt.Columns, sqlgraph.NewFieldSpec(deliveryattempt.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DeliveryAttempt.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deliveryattempt.FieldID)
		for _, f := range fields {
			if !deliveryattempt.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != deliveryattempt.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &DeliveryAttempt{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deliveryattempt.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
