// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"notifex/ent/notificationlog"
	"notifex/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NotificationLogDelete is the builder for deleting a NotificationLog entity.
type NotificationLogDelete struct {
	config
	hooks    []Hook
	mutation *NotificationLogMutation
}

// Where appends a list predicates to the NotificationLogDelete builder.
func (_d *NotificationLogDelete) Where(ps ...predicate.NotificationLog) *NotificationLogDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *NotificationLogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NotificationLogDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *NotificationLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(notificationlog.Table, sqlgraph.NewFieldSpec(notificationlog.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// NotificationLogDeleteOne is the builder for deleting a single NotificationLog entity.
type NotificationLogDeleteOne struct {
	_d *NotificationLogDelete
}

// Where appends a list predicates to the NotificationLogDelete builder.
func (_d *NotificationLogDeleteOne) Where(ps ...predicate.NotificationLog) *NotificationLogDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *NotificationLogDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{notificationlog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NotificationLogDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
