// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"notifex/ent/app"
	"notifex/ent/notification"
	"notifex/ent/notificationlog"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// NotificationLogCreate is the builder for creating a NotificationLog entity.
type NotificationLogCreate struct {
	config
	mutation *NotificationLogMutation
	hooks    []Hook
}

// SetNotificationID sets the "notification_id" field.
func (_c *NotificationLogCreate) SetNotificationID(v uuid.UUID) *NotificationLogCreate {
	_c.mutation.SetNotificationID(v)
	return _c
}

// SetAppID sets the "app_id" field.
func (_c *NotificationLogCreate) SetAppID(v uuid.UUID) *NotificationLogCreate {
	_c.mutation.SetAppID(v)
	return _c
}

// SetChannel sets the "channel" field.
func (_c *NotificationLogCreate) SetChannel(v notificationlog.Channel) *NotificationLogCreate {
	_c.mutation.SetChannel(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *NotificationLogCreate) SetProvider(v string) *NotificationLogCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *NotificationLogCreate) SetNillableProvider(v *string) *NotificationLogCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *NotificationLogCreate) SetStatus(v notificationlog.Status) *NotificationLogCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *NotificationLogCreate) SetNillableStatus(v *notificationlog.Status) *NotificationLogCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetProviderMessageID sets the "provider_message_id" field.
func (_c *NotificationLogCreate) SetProviderMessageID(v string) *NotificationLogCreate {
	_c.mutation.SetProviderMessageID(v)
	return _c
}

// SetNillableProviderMessageID sets the "provider_message_id" field if the given value is not nil.
func (_c *NotificationLogCreate) SetNillableProviderMessageID(v *string) *NotificationLogCreate {
	if v != nil {
		_c.SetProviderMessageID(*v)
	}
	return _c
}

// SetRenderedSubject sets the "rendered_subject" field.
func (_c *NotificationLogCreate) SetRenderedSubject(v string) *NotificationLogCreate {
	_c.mutation.SetRenderedSubject(v)
	return _c
}

// SetNillableRenderedSubject sets the "rendered_subject" field if the given value is not nil.
func (_c *NotificationLogCreate) SetNillableRenderedSubject(v *string) *NotificationLogCreate {
	if v != nil {
		_c.SetRenderedSubject(*v)
	}
	return _c
}

// SetRenderedBody sets the "rendered_body" field.
func (_c *NotificationLogCreate) SetRenderedBody(v string) *NotificationLogCreate {
	_c.mutation.SetRenderedBody(v)
	return _c
}

// SetNillableRenderedBody sets the "rendered_body" field if the given value is not nil.
func (_c *NotificationLogCreate) SetNillableRenderedBody(v *string) *NotificationLogCreate {
	if v != nil {
		_c.SetRenderedBody(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *NotificationLogCreate) SetCreatedAt(v time.Time) *NotificationLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NotificationLogCreate) SetNillableCreatedAt(v *time.Time) *NotificationLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *NotificationLogCreate) SetUpdatedAt(v time.Time) *NotificationLogCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *NotificationLogCreate) SetNillableUpdatedAt(v *time.Time) *NotificationLogCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *NotificationLogCreate) SetID(v uuid.UUID) *NotificationLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *NotificationLogCreate) SetNillableID(v *uuid.UUID) *NotificationLogCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddNotificationIDs adds the "notification" edge to the Notification entity by IDs.
func (_c *NotificationLogCreate) AddNotificationIDs(ids ...uuid.UUID) *NotificationLogCreate {
	_c.mutation.AddNotificationIDs(ids...)
	return _c
}

// AddNotification adds the "notification" edges to the Notification entity.
func (_c *NotificationLogCreate) AddNotification(v ...*Notification) *NotificationLogCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddNotificationIDs(ids...)
}

// AddAppIDs adds the "app" edge to the App entity by IDs.
func (_c *NotificationLogCreate) AddAppIDs(ids ...uuid.UUID) *NotificationLogCreate {
	_c.mutation.AddAppIDs(ids...)
	return _c
}

// AddApp adds the "app" edges to the App entity.
func (_c *NotificationLogCreate) AddApp(v ...*App) *NotificationLogCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAppIDs(ids...)
}

// Mutation returns the NotificationLogMutation object of the builder.
func (_c *NotificationLogCreate) Mutation() *NotificationLogMutation {
	return _c.mutation
}

// Save creates the NotificationLog in the database.
func (_c *NotificationLogCreate) Save(ctx context.Context) (*NotificationLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NotificationLogCreate) SaveX(ctx context.Context) *NotificationLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NotificationLogCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := notificationlog.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := notificationlog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := notificationlog.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := notificationlog.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NotificationLogCreate) check() error {
	if _, ok := _c.mutation.NotificationID(); !ok {
		return &ValidationError{Name: "notification_id", err: errors.New(`ent: missing required field "NotificationLog.notification_id"`)}
	}
	if _, ok := _c.mutation.AppID(); !ok {
		return &ValidationError{Name: "app_id", err: errors.New(`ent: missing required field "NotificationLog.app_id"`)}
	}
	if _, ok := _c.mutation.Channel(); !ok {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required field "NotificationLog.channel"`)}
	}
	if v, ok := _c.mutation.Channel(); ok {
		if err := notificationlog.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "NotificationLog.channel": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := notificationlog.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "NotificationLog.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "NotificationLog.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := notificationlog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "NotificationLog.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ProviderMessageID(); ok {
		if err := notificationlog.ProviderMessageIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_message_id", err: fmt.Errorf(`ent: validator failed for field "NotificationLog.provider_message_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "NotificationLog.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "NotificationLog.updated_at"`)}
	}
	if len(_c.mutation.NotificationIDs()) == 0 {
		return &ValidationError{Name: "notification", err: errors.New(`ent: missing required edge "NotificationLog.notification"`)}
	}
	if len(_c.mutation.AppIDs()) == 0 {
		return &ValidationError{Name: "app", err: errors.New(`ent: missing required edge "NotificationLog.app"`)}
	}
	return nil
}

func (_c *NotificationLogCreate) sqlSave(ctx context.Context) (*NotificationLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NotificationLogCreate) createSpec() (*NotificationLog, *sqlgraph.CreateSpec) {
	var (
		_node = &NotificationLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(notificationlog.Table, sqlgraph.NewFieldSpec(notificationlog.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.NotificationID(); ok {
		_spec.SetField(notificationlog.FieldNotificationID, field.TypeUUID, value)
		_node.NotificationID = value
	}
	if value, ok := _c.mutation.AppID(); ok {
		_spec.SetField(notificationlog.FieldAppID, field.TypeUUID, value)
		_node.AppID = value
	}
	if value, ok := _c.mutation.Channel(); ok {
		_spec.SetField(notificationlog.FieldChannel, field.TypeEnum, value)
		_node.Channel = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(notificationlog.FieldProvider, field.TypeString, value)
		_node.Provider = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(notificationlog.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ProviderMessageID(); ok {
		_spec.SetField(notificationlog.FieldProviderMessageID, field.TypeString, value)
		_node.ProviderMessageID = &value
	}
	if value, ok := _c.mutation.RenderedSubject(); ok {
		_spec.SetField(notificationlog.FieldRenderedSubject, field.TypeString, value)
		_node.RenderedSubject = &value
	}
	if value, ok := _c.mutation.RenderedBody(); ok {
		_spec.SetField(notificationlog.FieldRenderedBody, field.TypeString, value)
		_node.RenderedBody = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(notificationlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationlog.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.NotificationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   notificationlog.NotificationTable,
			Columns: notificationlog.NotificationPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   notificationlog.AppTable,
			Columns: notificationlog.AppPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// NotificationLogCreateBulk is the builder for creating many NotificationLog entities in bulk.
type NotificationLogCreateBulk struct {
	config
	err      error
	builders []*NotificationLogCreate
}

// Save creates the NotificationLog entities in the database.
func (_c *NotificationLogCreateBulk) Save(ctx context.Context) ([]*NotificationLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NotificationLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NotificationLogCreateBulk) SaveX(ctx context.Context) []*NotificationLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
