// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"notifex/ent/notification"
	"notifex/ent/notificationlog"
	"notifex/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// NotificationUpdate is the builder for updating Notification entities.
type NotificationUpdate struct {
	config
	hooks    []Hook
	mutation *NotificationMutation
}

// Where appends a list predicates to the NotificationUpdate builder.
func (_u *NotificationUpdate) Where(ps ...predicate.Notification) *NotificationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTemplateID sets the "template_id" field.
func (_u *NotificationUpdate) SetTemplateID(v uuid.UUID) *NotificationUpdate {
	_u.mutation.SetTemplateID(v)
	return _u
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableTemplateID(v *uuid.UUID) *NotificationUpdate {
	if v != nil {
		_u.SetTemplateID(*v)
	}
	return _u
}

// ClearTemplateID clears the value of the "template_id" field.
func (_u *NotificationUpdate) ClearTemplateID() *NotificationUpdate {
	_u.mutation.ClearTemplateID()
	return _u
}

// SetData sets the "data" field.
func (_u *NotificationUpdate) SetData(v map[string]interface{}) *NotificationUpdate {
	_u.mutation.SetData(v)
	return _u
}

// ClearData clears the value of the "data" field.
func (_u *NotificationUpdate) ClearData() *NotificationUpdate {
	_u.mutation.ClearData()
	return _u
}

// SetChannels sets the "channels" field.
func (_u *NotificationUpdate) SetChannels(v []string) *NotificationUpdate {
	_u.mutation.SetChannels(v)
	return _u
}

// AppendChannels appends value to the "channels" field.
func (_u *NotificationUpdate) AppendChannels(v []string) *NotificationUpdate {
	_u.mutation.AppendChannels(v)
	return _u
}

// ClearChannels clears the value of the "channels" field.
func (_u *NotificationUpdate) ClearChannels() *NotificationUpdate {
	_u.mutation.ClearChannels()
	return _u
}

// SetStatus sets the "status" field.
func (_u *NotificationUpdate) SetStatus(v notification.Status) *NotificationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableStatus(v *notification.Status) *NotificationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *NotificationUpdate) SetMetadata(v map[string]interface{}) *NotificationUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *NotificationUpdate) ClearMetadata() *NotificationUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetDeliveredAt sets the "delivered_at" field.
func (_u *NotificationUpdate) SetDeliveredAt(v time.Time) *NotificationUpdate {
	_u.mutation.SetDeliveredAt(v)
	return _u
}

// SetNillableDeliveredAt sets the "delivered_at" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableDeliveredAt(v *time.Time) *NotificationUpdate {
	if v != nil {
		_u.SetDeliveredAt(*v)
	}
	return _u
}

// ClearDeliveredAt clears the value of the "delivered_at" field.
func (_u *NotificationUpdate) ClearDeliveredAt() *NotificationUpdate {
	_u.mutation.ClearDeliveredAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotificationUpdate) SetUpdatedAt(v time.Time) *NotificationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddNotificationlogIDs adds the "notificationlog" edge to the NotificationLog entity by IDs.
func (_u *NotificationUpdate) AddNotificationlogIDs(ids ...uuid.UUID) *NotificationUpdate {
	_u.mutation.AddNotificationlogIDs(ids...)
	return _u
}

// AddNotificationlog adds the "notificationlog" edges to the NotificationLog entity.
func (_u *NotificationUpdate) AddNotificationlog(v ...*NotificationLog) *NotificationUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNotificationlogIDs(ids...)
}

// Mutation returns the NotificationMutation object of the builder.
func (_u *NotificationUpdate) Mutation() *NotificationMutation {
	return _u.mutation
}

// ClearNotificationlog clears all "notificationlog" edges to the NotificationLog entity.
func (_u *NotificationUpdate) ClearNotificationlog() *NotificationUpdate {
	_u.mutation.ClearNotificationlog()
	return _u
}

// RemoveNotificationlogIDs removes the "notificationlog" edge to NotificationLog entities by IDs.
func (_u *NotificationUpdate) RemoveNotificationlogIDs(ids ...uuid.UUID) *NotificationUpdate {
	_u.mutation.RemoveNotificationlogIDs(ids...)
	return _u
}

// RemoveNotificationlog removes "notificationlog" edges to NotificationLog entities.
func (_u *NotificationUpdate) RemoveNotificationlog(v ...*NotificationLog) *NotificationUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNotificationlogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotificationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotificationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NotificationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := notification.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := notification.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Notification.status": %w`, err)}
		}
	}
	if _u.mutation.AppCleared() && len(_u.mutation.AppIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Notification.app"`)
	}
	return nil
}

func (_u *NotificationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TemplateID(); ok {
		_spec.SetField(notification.FieldTemplateID, field.TypeUUID, value)
	}
	if _u.mutation.TemplateIDCleared() {
		_spec.ClearField(notification.FieldTemplateID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(notification.FieldData, field.TypeJSON, value)
	}
	if _u.mutation.DataCleared() {
		_spec.ClearField(notification.FieldData, field.TypeJSON)
	}
	if value, ok := _u.mutation.Channels(); ok {
		_spec.SetField(notification.FieldChannels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedChannels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, notification.FieldChannels, value)
		})
	}
	if _u.mutation.ChannelsCleared() {
		_spec.ClearField(notification.FieldChannels, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(notification.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(notification.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(notification.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.DeliveredAt(); ok {
		_spec.SetField(notification.FieldDeliveredAt, field.TypeTime, value)
	}
	if _u.mutation.DeliveredAtCleared() {
		_spec.ClearField(notification.FieldDeliveredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notification.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.NotificationlogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   notification.NotificationlogTable,
			Columns: notification.NotificationlogPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationlog.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNotificationlogIDs(); len(nodes) > 0 && !_u.mutation.NotificationlogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   notification.NotificationlogTable,
			Columns: notification.NotificationlogPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationlog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NotificationlogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   notification.NotificationlogTable,
			Columns: notification.NotificationlogPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationlog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotificationUpdateOne is the builder for updating a single Notification entity.
type NotificationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotificationMutation
}

// SetTemplateID sets the "template_id" field.
func (_u *NotificationUpdateOne) SetTemplateID(v uuid.UUID) *NotificationUpdateOne {
	_u.mutation.SetTemplateID(v)
	return _u
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableTemplateID(v *uuid.UUID) *NotificationUpdateOne {
	if v != nil {
		_u.SetTemplateID(*v)
	}
	return _u
}

// ClearTemplateID clears the value of the "template_id" field.
func (_u *NotificationUpdateOne) ClearTemplateID() *NotificationUpdateOne {
	_u.mutation.ClearTemplateID()
	return _u
}

// SetData sets the "data" field.
func (_u *NotificationUpdateOne) SetData(v map[string]interface{}) *NotificationUpdateOne {
	_u.mutation.SetData(v)
	return _u
}

// ClearData clears the value of the "data" field.
func (_u *NotificationUpdateOne) ClearData() *NotificationUpdateOne {
	_u.mutation.ClearData()
	return _u
}

// SetChannels sets the "channels" field.
func (_u *NotificationUpdateOne) SetChannels(v []string) *NotificationUpdateOne {
	_u.mutation.SetChannels(v)
	return _u
}

// AppendChannels appends value to the "channels" field.
func (_u *NotificationUpdateOne) AppendChannels(v []string) *NotificationUpdateOne {
	_u.mutation.AppendChannels(v)
	return _u
}

// ClearChannels clears the value of the "channels" field.
func (_u *NotificationUpdateOne) ClearChannels() *NotificationUpdateOne {
	_u.mutation.ClearChannels()
	return _u
}

// SetStatus sets the "status" field.
func (_u *NotificationUpdateOne) SetStatus(v notification.Status) *NotificationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableStatus(v *notification.Status) *NotificationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *NotificationUpdateOne) SetMetadata(v map[string]interface{}) *NotificationUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *NotificationUpdateOne) ClearMetadata() *NotificationUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetDeliveredAt sets the "delivered_at" field.
func (_u *NotificationUpdateOne) SetDeliveredAt(v time.Time) *NotificationUpdateOne {
	_u.mutation.SetDeliveredAt(v)
	return _u
}

// SetNillableDeliveredAt sets the "delivered_at" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableDeliveredAt(v *time.Time) *NotificationUpdateOne {
	if v != nil {
		_u.SetDeliveredAt(*v)
	}
	return _u
}

// ClearDeliveredAt clears the value of the "delivered_at" field.
func (_u *NotificationUpdateOne) ClearDeliveredAt() *NotificationUpdateOne {
	_u.mutation.ClearDeliveredAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotificationUpdateOne) SetUpdatedAt(v time.Time) *NotificationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddNotificationlogIDs adds the "notificationlog" edge to the NotificationLog entity by IDs.
func (_u *NotificationUpdateOne) AddNotificationlogIDs(ids ...uuid.UUID) *NotificationUpdateOne {
	_u.mutation.AddNotificationlogIDs(ids...)
	return _u
}

// AddNotificationlog adds the "notificationlog" edges to the NotificationLog entity.
func (_u *NotificationUpdateOne) AddNotificationlog(v ...*NotificationLog) *NotificationUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNotificationlogIDs(ids...)
}

// Mutation returns the NotificationMutation object of the builder.
func (_u *NotificationUpdateOne) Mutation() *NotificationMutation {
	return _u.mutation
}

// ClearNotificationlog clears all "notificationlog" edges to the NotificationLog entity.
func (_u *NotificationUpdateOne) ClearNotificationlog() *NotificationUpdateOne {
	_u.mutation.ClearNotificationlog()
	return _u
}

// RemoveNotificationlogIDs removes the "notificationlog" edge to NotificationLog entities by IDs.
func (_u *NotificationUpdateOne) RemoveNotificationlogIDs(ids ...uuid.UUID) *NotificationUpdateOne {
	_u.mutation.RemoveNotificationlogIDs(ids...)
	return _u
}

// RemoveNotificationlog removes "notificationlog" edges to NotificationLog entities.
func (_u *NotificationUpdateOne) RemoveNotificationlog(v ...*NotificationLog) *NotificationUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNotificationlogIDs(ids...)
}

// Where appends a list predicates to the NotificationUpdate builder.
func (_u *NotificationUpdateOne) Where(ps ...predicate.Notification) *NotificationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotificationUpdateOne) Select(field string, fields ...string) *NotificationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Notification entity.
func (_u *NotificationUpdateOne) Save(ctx context.Context) (*Notification, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationUpdateOne) SaveX(ctx context.Context) *Notification {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotificationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NotificationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := notification.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := notification.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Notification.status": %w`, err)}
		}
	}
	if _u.mutation.AppCleared() && len(_u.mutation.AppIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Notification.app"`)
	}
	return nil
}

func (_u *NotificationUpdateOne) sqlSave(ctx context.Context) (_node *Notification, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Notification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notification.FieldID)
		for _, f := range fields {
			if !notification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TemplateID(); ok {
		_spec.SetField(notification.FieldTemplateID, field.TypeUUID, value)
	}
	if _u.mutation.TemplateIDCleared() {
		_spec.ClearField(notification.FieldTemplateID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(notification.FieldData, field.TypeJSON, value)
	}
	if _u.mutation.DataCleared() {
		_spec.ClearField(notification.FieldData, field.TypeJSON)
	}
	if value, ok := _u.mutation.Channels(); ok {
		_spec.SetField(notification.FieldChannels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedChannels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, notification.FieldChannels, value)
		})
	}
	if _u.mutation.ChannelsCleared() {
		_spec.ClearField(notification.FieldChannels, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(notification.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(notification.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(notification.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.DeliveredAt(); ok {
		_spec.SetField(notification.FieldDeliveredAt, field.TypeTime, value)
	}
	if _u.mutation.DeliveredAtCleared() {
		_spec.ClearField(notification.FieldDeliveredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notification.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.NotificationlogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   notification.NotificationlogTable,
			Columns: notification.NotificationlogPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationlog.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNotificationlogIDs(); len(nodes) > 0 && !_u.mutation.NotificationlogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   notification.NotificationlogTable,
			Columns: notification.NotificationlogPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationlog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NotificationlogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   notification.NotificationlogTable,
			Columns: notification.NotificationlogPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationlog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Notification{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
