// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"notifex/ent/predicate"
	"notifex/ent/securityauditlog"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SecurityAuditLogUpdate is the builder for updating SecurityAuditLog entities.
type SecurityAuditLogUpdate struct {
	config
	hooks    []Hook
	mutation *SecurityAuditLogMutation
}

// Where appends a list predicates to the SecurityAuditLogUpdate builder.
func (_u *SecurityAuditLogUpdate) Where(ps ...predicate.SecurityAuditLog) *SecurityAuditLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the SecurityAuditLogMutation object of the builder.
func (_u *SecurityAuditLogUpdate) Mutation() *SecurityAuditLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SecurityAuditLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SecurityAuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SecurityAuditLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SecurityAuditLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SecurityAuditLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(securityauditlog.Table, securityauditlog.Columns, sqlgraph.NewFieldSpec(securityauditlog.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{securityauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SecurityAuditLogUpdateOne is the builder for updating a single SecurityAuditLog entity.
type SecurityAuditLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SecurityAuditLogMutation
}

// Mutation returns the SecurityAuditLogMutation object of the builder.
func (_u *SecurityAuditLogUpdateOne) Mutation() *SecurityAuditLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the SecurityAuditLogUpdate builder.
func (_u *SecurityAuditLogUpdateOne) Where(ps ...predicate.SecurityAuditLog) *SecurityAuditLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SecurityAuditLogUpdateOne) Select(field string, fields ...string) *SecurityAuditLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SecurityAuditLog entity.
func (_u *SecurityAuditLogUpdateOne) Save(ctx context.Context) (*SecurityAuditLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SecurityAuditLogUpdateOne) SaveX(ctx context.Context) *SecurityAuditLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SecurityAuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SecurityAuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SecurityAuditLogUpdateOne) sqlSave(ctx context.Context) (_node *SecurityAuditLog, err error) {
	_spec := sqlgraph.NewUpdateSpec(securityauditlog.Table, securityauditlog.Columns, sqlgraph.NewFieldSpec(securityauditlog.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SecurityAuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, securityauditlog.FieldID)
		for _, f := range fields {
			if !securityauditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != securityauditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &SecurityAuditLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{securityauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
