// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"notifex/ent/template"
	"notifex/ent/templatecontent"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TemplateContentCreate is the builder for creating a TemplateContent entity.
type TemplateContentCreate struct {
	config
	mutation *TemplateContentMutation
	hooks    []Hook
}

// SetTemplateID sets the "template_id" field.
func (_c *TemplateContentCreate) SetTemplateID(v uuid.UUID) *TemplateContentCreate {
	_c.mutation.SetTemplateID(v)
	return _c
}

// SetChannel sets the "channel" field.
func (_c *TemplateContentCreate) SetChannel(v templatecontent.Channel) *TemplateContentCreate {
	_c.mutation.SetChannel(v)
	return _c
}

// SetSubject sets the "subject" field.
func (_c *TemplateContentCreate) SetSubject(v string) *TemplateContentCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_c *TemplateContentCreate) SetNillableSubject(v *string) *TemplateContentCreate {
	if v != nil {
		_c.SetSubject(*v)
	}
	return _c
}

// SetBodyText sets the "body_text" field.
func (_c *TemplateContentCreate) SetBodyText(v string) *TemplateContentCreate {
	_c.mutation.SetBodyText(v)
	return _c
}

// SetBodyHTML sets the "body_html" field.
func (_c *TemplateContentCreate) SetBodyHTML(v string) *TemplateContentCreate {
	_c.mutation.SetBodyHTML(v)
	return _c
}

// SetNillableBodyHTML sets the "body_html" field if the given value is not nil.
func (_c *TemplateContentCreate) SetNillableBodyHTML(v *string) *TemplateContentCreate {
	if v != nil {
		_c.SetBodyHTML(*v)
	}
	return _c
}

// SetExtras sets the "extras" field.
func (_c *TemplateContentCreate) SetExtras(v map[string]interface{}) *TemplateContentCreate {
	_c.mutation.SetExtras(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TemplateContentCreate) SetCreatedAt(v time.Time) *TemplateContentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TemplateContentCreate) SetNillableCreatedAt(v *time.Time) *TemplateContentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TemplateContentCreate) SetUpdatedAt(v time.Time) *TemplateContentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TemplateContentCreate) SetNillableUpdatedAt(v *time.Time) *TemplateContentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TemplateContentCreate) SetID(v uuid.UUID) *TemplateContentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TemplateContentCreate) SetNillableID(v *uuid.UUID) *TemplateContentCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetTemplate sets the "template" edge to the Template entity.
func (_c *TemplateContentCreate) SetTemplate(v *Template) *TemplateContentCreate {
	return _c.SetTemplateID(v.ID)
}

// Mutation returns the TemplateContentMutation object of the builder.
func (_c *TemplateContentCreate) Mutation() *TemplateContentMutation {
	return _c.mutation
}

// Save creates the TemplateContent in the database.
func (_c *TemplateContentCreate) Save(ctx context.Context) (*TemplateContent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TemplateContentCreate) SaveX(ctx context.Context) *TemplateContent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TemplateContentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TemplateContentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TemplateContentCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := templatecontent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := templatecontent.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := templatecontent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TemplateContentCreate) check() error {
	if _, ok := _c.mutation.TemplateID(); !ok {
		return &ValidationError{Name: "template_id", err: errors.New(`ent: missing required field "TemplateContent.template_id"`)}
	}
	if _, ok := _c.mutation.Channel(); !ok {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required field "TemplateContent.channel"`)}
	}
	if v, ok := _c.mutation.Channel(); ok {
		if err := templatecontent.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "TemplateContent.channel": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Subject(); ok {
		if err := templatecontent.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "TemplateContent.subject": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BodyText(); !ok {
		return &ValidationError{Name: "body_text", err: errors.New(`ent: missing required field "TemplateContent.body_text"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TemplateContent.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TemplateContent.updated_at"`)}
	}
	if len(_c.mutation.TemplateIDs()) == 0 {
		return &ValidationError{Name: "template", err: errors.New(`ent: missing required edge "TemplateContent.template"`)}
	}
	return nil
}

func (_c *TemplateContentCreate) sqlSave(ctx context.Context) (*TemplateContent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TemplateContentCreate) createSpec() (*TemplateContent, *sqlgraph.CreateSpec) {
	var (
		_node = &TemplateContent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(templatecontent.Table, sqlgraph.NewFieldSpec(templatecontent.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Channel(); ok {
		_spec.SetField(templatecontent.FieldChannel, field.TypeEnum, value)
		_node.Channel = value
	}
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(templatecontent.FieldSubject, field.TypeString, value)
		_node.Subject = &value
	}
	if value, ok := _c.mutation.BodyText(); ok {
		_spec.SetField(templatecontent.FieldBodyText, field.TypeString, value)
		_node.BodyText = value
	}
	if value, ok := _c.mutation.BodyHTML(); ok {
		_spec.SetField(templatecontent.FieldBodyHTML, field.TypeString, value)
		_node.BodyHTML = &value
	}
	if value, ok := _c.mutation.Extras(); ok {
		_spec.SetField(templatecontent.FieldExtras, field.TypeJSON, value)
		_node.Extras = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(templatecontent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(templatecontent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TemplateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   templatecontent.TemplateTable,
			Columns: []string{templatecontent.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TemplateID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TemplateContentCreateBulk is the builder for creating many TemplateContent entities in bulk.
type TemplateContentCreateBulk struct {
	config
	err      error
	builders []*TemplateContentCreate
}

// Save creates the TemplateContent entities in the database.
func (_c *TemplateContentCreateBulk) Save(ctx context.Context) ([]*TemplateContent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TemplateContent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TemplateContentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TemplateContentCreateBulk) SaveX(ctx context.Context) []*TemplateContent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TemplateContentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TemplateContentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
