// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"notifex/ent/usercredential"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UserCredential is the model entity for the UserCredential schema.
type UserCredential struct {
	config
	// ID of the ent.
	ID           int `json:"id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserCredential) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usercredential.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserCredential fields.
func (_m *UserCredential) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usercredential.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserCredential.
// This includes values selected through modifiers, order, etc.
func (_m *UserCredential) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UserCredential.
// Note that you need to call UserCredential.Unwrap() before calling this method if this UserCredential
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserCredential) Update() *UserCredentialUpdateOne {
	return NewUserCredentialClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserCredential entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserCredential) Unwrap() *UserCredential {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserCredential is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserCredential) String() string {
	var builder strings.Builder
	builder.WriteString("UserCredential(")
	builder.WriteString(fmt.Sprintf("id=%v", _m.ID))
	builder.WriteByte(')')
	return builder.String()
}

// UserCredentials is a parsable slice of UserCredential.
type UserCredentials []*UserCredential
