// Code generated by ent, DO NOT EDIT.

package app

import (
	"notifex/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.App {
	return predicate.App(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.App {
	return predicate.App(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.App {
	return predicate.App(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.App {
	return predicate.App(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.App {
	return predicate.App(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.App {
	return predicate.App(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.App {
	return predicate.App(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldName, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldSlug, v))
}

// MonthlyQuota applies equality check predicate on the "monthly_quota" field. It's identical to MonthlyQuotaEQ.
func MonthlyQuota(v int) predicate.App {
	return predicate.App(sql.FieldEQ(FieldMonthlyQuota, v))
}

// QuotaUsed applies equality check predicate on the "quota_used" field. It's identical to QuotaUsedEQ.
func QuotaUsed(v int) predicate.App {
	return predicate.App(sql.FieldEQ(FieldQuotaUsed, v))
}

// QuotaResetAt applies equality check predicate on the "quota_reset_at" field. It's identical to QuotaResetAtEQ.
func QuotaResetAt(v time.Time) predicate.App {
	return predicate.App(sql.FieldEQ(FieldQuotaResetAt, v))
}

// Active applies equality check predicate on the "active" field. It's identical to ActiveEQ.
func Active(v bool) predicate.App {
	return predicate.App(sql.FieldEQ(FieldActive, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.App {
	return predicate.App(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.App {
	return predicate.App(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldName, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldSlug, v))
}

// PlanEQ applies the EQ predicate on the "plan" field.
func PlanEQ(v Plan) predicate.App {
	return predicate.App(sql.FieldEQ(FieldPlan, v))
}

// PlanNEQ applies the NEQ predicate on the "plan" field.
func PlanNEQ(v Plan) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldPlan, v))
}

// PlanIn applies the In predicate on the "plan" field.
func PlanIn(vs ...Plan) predicate.App {
	return predicate.App(sql.FieldIn(FieldPlan, vs...))
}

// PlanNotIn applies the NotIn predicate on the "plan" field.
func PlanNotIn(vs ...Plan) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldPlan, vs...))
}

// MonthlyQuotaEQ applies the EQ predicate on the "monthly_quota" field.
func MonthlyQuotaEQ(v int) predicate.App {
	return predicate.App(sql.FieldEQ(FieldMonthlyQuota, v))
}

// MonthlyQuotaNEQ applies the NEQ predicate on the "monthly_quota" field.
func MonthlyQuotaNEQ(v int) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldMonthlyQuota, v))
}

// MonthlyQuotaIn applies the In predicate on the "monthly_quota" field.
func MonthlyQuotaIn(vs ...int) predicate.App {
	return predicate.App(sql.FieldIn(FieldMonthlyQuota, vs...))
}

// MonthlyQuotaNotIn applies the NotIn predicate on the "monthly_quota" field.
func MonthlyQuotaNotIn(vs ...int) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldMonthlyQuota, vs...))
}

// MonthlyQuotaGT applies the GT predicate on the "monthly_quota" field.
func MonthlyQuotaGT(v int) predicate.App {
	return predicate.App(sql.FieldGT(FieldMonthlyQuota, v))
}

// MonthlyQuotaGTE applies the GTE predicate on the "monthly_quota" field.
func MonthlyQuotaGTE(v int) predicate.App {
	return predicate.App(sql.FieldGTE(FieldMonthlyQuota, v))
}

// MonthlyQuotaLT applies the LT predicate on the "monthly_quota" field.
func MonthlyQuotaLT(v int) predicate.App {
	return predicate.App(sql.FieldLT(FieldMonthlyQuota, v))
}

// MonthlyQuotaLTE applies the LTE predicate on the "monthly_quota" field.
func MonthlyQuotaLTE(v int) predicate.App {
	return predicate.App(sql.FieldLTE(FieldMonthlyQuota, v))
}

// QuotaUsedEQ applies the EQ predicate on the "quota_used" field.
func QuotaUsedEQ(v int) predicate.App {
	return predicate.App(sql.FieldEQ(FieldQuotaUsed, v))
}

// QuotaUsedNEQ applies the NEQ predicate on the "quota_used" field.
func QuotaUsedNEQ(v int) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldQuotaUsed, v))
}

// QuotaUsedIn applies the In predicate on the "quota_used" field.
func QuotaUsedIn(vs ...int) predicate.App {
	return predicate.App(sql.FieldIn(FieldQuotaUsed, vs...))
}

// QuotaUsedNotIn applies the NotIn predicate on the "quota_used" field.
func QuotaUsedNotIn(vs ...int) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldQuotaUsed, vs...))
}

// QuotaUsedGT applies the GT predicate on the "quota_used" field.
func QuotaUsedGT(v int) predicate.App {
	return predicate.App(sql.FieldGT(FieldQuotaUsed, v))
}

// QuotaUsedGTE applies the GTE predicate on the "quota_used" field.
func QuotaUsedGTE(v int) predicate.App {
	return predicate.App(sql.FieldGTE(FieldQuotaUsed, v))
}

// QuotaUsedLT applies the LT predicate on the "quota_used" field.
func QuotaUsedLT(v int) predicate.App {
	return predicate.App(sql.FieldLT(FieldQuotaUsed, v))
}

// QuotaUsedLTE applies the LTE predicate on the "quota_used" field.
func QuotaUsedLTE(v int) predicate.App {
	return predicate.App(sql.FieldLTE(FieldQuotaUsed, v))
}

// QuotaResetAtEQ applies the EQ predicate on the "quota_reset_at" field.
func QuotaResetAtEQ(v time.Time) predicate.App {
	return predicate.App(sql.FieldEQ(FieldQuotaResetAt, v))
}

// QuotaResetAtNEQ applies the NEQ predicate on the "quota_reset_at" field.
func QuotaResetAtNEQ(v time.Time) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldQuotaResetAt, v))
}

// QuotaResetAtIn applies the In predicate on the "quota_reset_at" field.
func QuotaResetAtIn(vs ...time.Time) predicate.App {
	return predicate.App(sql.FieldIn(FieldQuotaResetAt, vs...))
}

// QuotaResetAtNotIn applies the NotIn predicate on the "quota_reset_at" field.
func QuotaResetAtNotIn(vs ...time.Time) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldQuotaResetAt, vs...))
}

// QuotaResetAtGT applies the GT predicate on the "quota_reset_at" field.
func QuotaResetAtGT(v time.Time) predicate.App {
	return predicate.App(sql.FieldGT(FieldQuotaResetAt, v))
}

// QuotaResetAtGTE applies the GTE predicate on the "quota_reset_at" field.
func QuotaResetAtGTE(v time.Time) predicate.App {
	return predicate.App(sql.FieldGTE(FieldQuotaResetAt, v))
}

// QuotaResetAtLT applies the LT predicate on the "quota_reset_at" field.
func QuotaResetAtLT(v time.Time) predicate.App {
	return predicate.App(sql.FieldLT(FieldQuotaResetAt, v))
}

// QuotaResetAtLTE applies the LTE predicate on the "quota_reset_at" field.
func QuotaResetAtLTE(v time.Time) predicate.App {
	return predicate.App(sql.FieldLTE(FieldQuotaResetAt, v))
}

// ActiveEQ applies the EQ predicate on the "active" field.
func ActiveEQ(v bool) predicate.App {
	return predicate.App(sql.FieldEQ(FieldActive, v))
}

// ActiveNEQ applies the NEQ predicate on the "active" field.
func ActiveNEQ(v bool) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.App {
	return predicate.App(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.App {
	return predicate.App(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.App {
	return predicate.App(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.App {
	return predicate.App(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.App {
	return predicate.App(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.App {
	return predicate.App(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.App {
	return predicate.App(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.App {
	return predicate.App(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.App {
	return predicate.App(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.App {
	return predicate.App(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.App {
	return predicate.App(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.App {
	return predicate.App(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasAPIKeys applies the HasEdge predicate on the "api_keys" edge.
func HasAPIKeys() predicate.App {
	return predicate.App(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, APIKeysTable, APIKeysColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeysWith applies the HasEdge predicate on the "api_keys" edge with a given conditions (other predicates).
func HasAPIKeysWith(preds ...predicate.APIKey) predicate.App {
	return predicate.App(func(s *sql.Selector) {
		step := newAPIKeysStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTemplates applies the HasEdge predicate on the "templates" edge.
func HasTemplates() predicate.App {
	return predicate.App(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TemplatesTable, TemplatesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTemplatesWith applies the HasEdge predicate on the "templates" edge with a given conditions (other predicates).
func HasTemplatesWith(preds ...predicate.Template) predicate.App {
	return predicate.App(func(s *sql.Selector) {
		step := newTemplatesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasNotifications applies the HasEdge predicate on the "notifications" edge.
func HasNotifications() predicate.App {
	return predicate.App(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, NotificationsTable, NotificationsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNotificationsWith applies the HasEdge predicate on the "notifications" edge with a given conditions (other predicates).
func HasNotificationsWith(preds ...predicate.Notification) predicate.App {
	return predicate.App(func(s *sql.Selector) {
		step := newNotificationsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasNotificationlog applies the HasEdge predicate on the "notificationlog" edge.
func HasNotificationlog() predicate.App {
	return predicate.App(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, NotificationlogTable, NotificationlogPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNotificationlogWith applies the HasEdge predicate on the "notificationlog" edge with a given conditions (other predicates).
func HasNotificationlogWith(preds ...predicate.NotificationLog) predicate.App {
	return predicate.App(func(s *sql.Selector) {
		step := newNotificationlogStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.App) predicate.App {
	return predicate.App(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.App) predicate.App {
	return predicate.App(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.App) predicate.App {
	return predicate.App(sql.NotPredicates(p))
}
