// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// APIKey is the predicate function for apikey builders.
type APIKey func(*sql.Selector)

// App is the predicate function for app builders.
type App func(*sql.Selector)

// Notification is the predicate function for notification builders.
type Notification func(*sql.Selector)

// NotificationLog is the predicate function for notificationlog builders.
type NotificationLog func(*sql.Selector)

// Template is the predicate function for template builders.
type Template func(*sql.Selector)

// TemplateContent is the predicate function for templatecontent builders.
type TemplateContent func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserSession is the predicate function for usersession builders.
type UserSession func(*sql.Selector)

// VerificationToken is the predicate function for verificationtoken builders.
type VerificationToken func(*sql.Selector)
